Repository tourstream/fti-portal-styleguide, pull requests merged in 2019-09, with the labels that each got.

#148 ETS-2257 fixes some indexes and defines them
  CHANGELOG.md
  source/scss/abstracts/_functions.scss
  source/scss/components/_backdrop.scss
  source/scss/components/_cookie-alert.scss
  source/scss/components/_header-logo.scss
  source/scss/components/_select.scss
  source/scss/components/header-menu/_header-menu.scss
  source/scss/components/header-menu/_header-sub-menu.scss
  source/scss/layout/_header.scss
  source/scss/variables/_custom-variables.scss
Labels: in QA/Approval

#149 ETS-2260 adapts headlines margin-bottoms
  CHANGELOG.md
  source/scss/typography/_typography.scss
  source/scss/variables/_typography-variables.scss
Labels: ready to merge

#150 ETS-2259 adapts headlines mobile line-heights
  CHANGELOG.md
  source/scss/typography/_typography.scss
  source/scss/variables/_typography-variables.scss
Labels: ready to merge

#151 ETS-2263 Defines margin-top for text-images and a bit of refactoring
  CHANGELOG.md
  source/scss/components/_text-image.scss
  source/scss/variables/_custom-variables.scss
Labels: ready to merge

#152 ETS-2254 Adds hover colour to offer teaser > linked price
  CHANGELOG.md
  source/_patterns/02-organisms/04-teaser/01-offer-teaser-50.mustache
  source/_patterns/04-pages/03-teaser.mustache
  source/scss/components/_teaser.scss
  source/scss/variables/_color-variables.scss
Labels: ready to merge

#153 ETS-2261 Adds atom divider (hr) and defines its margins
  CHANGELOG.md
  source/_patterns/00-atoms/03-components/02-divider.md
  source/_patterns/00-atoms/03-components/02-divider.mustache
  source/_patterns/03-templates/standard.mustache
  source/_patterns/04-pages/01-crisis-information.mustache
  source/_patterns/04-pages/03-multioffer-teaser.mustache
  source/_patterns/04-pages/03-teaser.mustache
  source/_patterns/04-pages/04-top-offer-list.mustache
  source/scss/layout/_divider.scss
  source/scss/style.scss
Labels: ready to merge

#155 ETS-2274 Adds general classes for element width
  CHANGELOG.md
  source/_patterns/03-templates/standard.mustache
  source/scss/layout/_main.scss
Labels: in QA/Approval

#154 Introduces proper SCSS documentation
  .gitignore
  README.md
  package-lock.json
  package.json
  scss-doc-config.json
  source/scss/abstracts/_functions.scss
  source/scss/abstracts/_helper-classes.scss
  source/scss/abstracts/_mixins.scss
  source/scss/layout/_body.scss
  source/scss/layout/_footer-navigation.scss
  source/scss/layout/_footer.scss
  source/scss/layout/_header.scss
  source/scss/layout/_main.scss
  source/scss/patternlab/_colors.scss
  source/scss/style.scss
  source/scss/typography/_component-typography.scss
  source/scss/typography/_typography.scss
  source/scss/variables/_color-variables.scss
  source/scss/variables/_custom-variables.scss
  source/scss/variables/_typography-variables.scss
Labels: enhancement
